version: '3.8'

services:
  web-api:
    build: ./app
    container_name: web-api-01-Sqlite-RawSQL
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network

  db-ui:
    image: coleifer/sqlite-web
    container_name: db-ui-01-Sqlite-RawSQL
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data
    networks:
      - app-network
    command: sqlite_web -H 0.0.0.0 -x /data/database.sqlite
    depends_on:
      - web-api

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
