version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-db-07-MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: itec617
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - db-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express-web-07-MongoDB
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - db-network

volumes:
  mongodb_data:

networks:
  db-network:
    driver: bridge
